name: deploy
on:
    push:
        branches:
            - main
jobs:
    build: 
        runs-on: self-hosted
        steps: 
            - uses: actions/checkout@v2
            - name: Copy .env
              run: cp varnen/.env actions-runner/_work/DE_P1/DE_P1/
            - name: PM2 Restart Server
              run: sudo pm2 restart server_node
            - name: PM2 Restart Sniffer
              run: sudo pm2 restart sniffer
