name: deploy
on:
    push:
        branches:
            -master
jobs:
    build: 
        runs-on: self-hosted
        steps: 
            - uses: actions/checkout@v2
            - name: PM2 Restart Server
              run: sudo pm2 restart server_node
            - name: PM2 Restart Sniffer
              run: sudo pm2 restart sniffer
