name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy_carlos:
    runs-on: carlosp
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp ~/varnen/.env .
      - name: PM2 Restart Server
        run: sudo pm2 restart server_node
      - name: PM2 Restart Sniffer
        run: sudo pm2 restart sniffer

  deploy_DE_runner:
    runs-on: MaicolLn
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp ~/varnen/.env .
      - name: PM2 Restart Server
        run: sudo pm2 restart server_node
      - name: PM2 Restart Sniffer
        run: sudo pm2 restart sniffer

  deploy_gabrielR:
    runs-on: gabrielR 
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: cp ~/varnen/.env .
      - name: PM2 Restart Server
        run: sudo pm2 restart server_node
      - name: PM2 Restart Sniffer
        run: sudo pm2 restart sniffer

              